#Deploying microservices for end-to-end testing
restfulservice:
  image:java:openjdk-8u45-jdk
  working_dir:/app
  volumes:
   -./spring-boot-restful-service/build/libs:/app
  command:java -jar /app/spring-boot-restful-service.ar
  ports:
   -"8081:8080"
  links:
   -rabbitmq
   -mongodb
  environment:
   SPRING_DATA_MONGODB_URI:mongodb://mongodb/userregistration
   SPRING_RABBITMQ_HOST:rabbitmq
